# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Name of your awesome conference
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/web-conference-theme/" # the subpath of your site, e.g. /blog
url: "https://gherardovarando.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

## enable jekyll-remote-theme 
plugins:
 - jekyll-feed
 - jekyll-seo-tag
# - jekyll-remote-theme  ## use remote theme 
#

## uncomment the following line 
# remote_theme: gherardovarando/web-conference-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


### defined for web-conference-theme

## set  timezone for handling default TZ for events and seminars
timezone: Europe/Madrid

## 
future: true
collections:
  days:
    output: true
    menu: true
    sort_by: date
    menu_label: Program
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "new"
  - scope:
      path: ""
      type: "days"
    values:
      layout: "default"

## short name of the conference
short: AwC2026
full: The 1st Awesome Conference
logo: assets/logo.png


## dates
dates:
- 2026-01-09
- 2026-01-10
- 2026-01-11


deadlines:
  # Fill in the key dates as below.
  # we use ISO8601 date and time format preferably  
  - name: Abstract submission deadline
    type: submission
    #text: Saturday, October 9, 2021, 11:59am UTC
    time: 2021-10-09 11:59Z 
    important: true
  - name: Paper submission deadline
    type: submission
    #text: Friday, October 15, 2021, 11:59am UTC  
    time: 2021-10-15 11:59Z
    important: true
  - name: Supplementary material submission
    type: submission
    #text: Friday, October 22, 2021, 11:59am UTC 
    time: 2021-10-22 11:59Z
  - name: Reviews released
    type: decision
    date: 2021-11-26
  - name: Author rebuttals due 
    #text: Sunday, December 5, 2021, 11:59am UTC
    time: 2021-12-05 11:59Z
    type: submission
  - name: Final decisions
    type: decision
    date: 2022-01-18
  - name: Camera-ready deadline
    type: submission 
    #text: Wednesday, February 23, 2022, 11:59am UTC
    time: 2022-02-23 11:59Z
  - name: Poster and thumbnail upload
    type: submission
    text: March 14th, 2022 (AOE)
  - name: SlidesLive last upload
    type: submission
    text: Wednesday, March 14, 2022 (AOE)
  - name: Conference dates
    text: January 09 - 11, 2026

chairs:
  - type: General Chair 
    people: 
    - name: William Sealy Gosset
      url: https://en.wikipedia.org/wiki/William_Sealy_Gosset
      affiliation: New College, Oxford
  - type: Program Chair 
    people: 
    - name: William Sealy Gosset
      url: https://en.wikipedia.org/wiki/William_Sealy_Gosset
      affiliation: New College, Oxford

links: 
   - name: twitter 
     url: https://twitter.com/jekyllrb
   - name: openreview 
     url: https://openreview.net/
